#!/bin/sh
# Start with a fresh OpenWrt (firstboot)
cp wicycle.sh /bin/wicycle
cp wicycle.awk /bin/wicycle.awk
cp wicycle /etc/init.d/wicycle
chmod a+x /bin/wicycle /etc/init.d/wicycle
ln -s ../init.d/wicycle /etc/rc.d/S70wicycle

# Optional:
#uci set 'system.@system[0].timezone'='EST5EDT,M3.2.0,M11.1.0' ; uci commit

